export const TOGGLE_PUSH_UP_NOTIFICATION_STATE = 'TOGGLE_PUSH_UP_NOTIFICATION_STATE'
export const SHOW_PUSH_UP_NOTIFICATION = 'SHOW_PUSH_UP_NOTIFICATION'
export const HIDE_PUSH_UP_NOTIFICATION = 'HIDE_PUSH_UP_NOTIFICATION' 